'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SunbreezeSerialTool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 group,code,des,type,len,link
        '''ModbusRTU_Fun,,,,,
        ''',01,读线圈,R,,
        ''',02,读输入离散量,R,,
        ''',03,读多个寄存器,R,,
        ''',04,读输入寄存器,R,,
        ''',05,写单个线圈,W,,
        ''',06,写单个寄存器,W,,
        ''',0F,写多个线圈,W,,
        ''',10,写多个寄存器,W,,
        ''',14,读文件记录,R,,
        ''',15,写文件记录,W,,
        ''',16,屏蔽写寄存器,W,,
        ''',17,读写多个寄存器,R,,
        ''',2B,读设备识别码,R,,
        ''',,,,,
        '''DLT645-1997_CTL,,,,,
        ''',01,读数据,R,2,9010
        ''',02,读后续数据,R,2,
        ''',03,重读数据,N,0,NULL
        ''',04,写数据,W,,
        ''',08,校时,W,6,NULL
        ''',0A,写设备地址,W,6,
        ''',0C,更改通信速率,W,1,
        ''',0F,改密码,W,4,
        ''',10,最大需量清零,N,0,NULL
        '''DLT645-1997_DI,,,,,
        ''',9010,正向有功总电能(+A),R,4,
        ''',9020,反向有功总电能(-A),R,4,
        ''',9110,正向无功总电能(+RL，+RC),R,4,
        ''',9120,反向无功总电 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property codelist() As String
            Get
                Return ResourceManager.GetString("codelist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CrcName,PolyDes,Width,PolyValue,InitValue,XorOutValue,RevIn,RevOut
        '''CRC-4/ITU,x4 + x + 1,4,3,0,0,TRUE,TRUE
        '''CRC-5/EPC,x5 + x3 + 1,5,9,9,0,FALSE,FALSE
        '''CRC-5/ITU,x5 + x4 + x2 + 1,5,15,0,0,TRUE,TRUE
        '''CRC-5/USB,x5 + x2 + 1,5,5,1F,1F,TRUE,TRUE
        '''CRC-6/ITU,x6 + x + 1,6,3,0,0,TRUE,TRUE
        '''CRC-7/MMC,x7 + x3 + 1,7,9,0,0,FALSE,FALSE
        '''CRC-8,x8 + x2 + x + 1,8,7,0,0,FALSE,FALSE
        '''CRC-8/ITU,x8 + x2 + x + 1,8,7,0,55,FALSE,FALSE
        '''CRC-8/ROHC,x8 + x2 + x + 1,8,7,FF,0,TRUE,TRUE
        '''CRC-8/MAXIM,x8 + x5 + x4 + 1,8,31,0,0,TRUE,TRUE
        '''CRC-16/IBM,x [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property crctable() As String
            Get
                Return ResourceManager.GetString("crctable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 FpName,Length,Exponent
        '''IEEE-FP32,32,8
        '''IEEE-FP64,64,11
        '''FP8,8,3
        '''IEEE-FP16,16,5
        '''CFloat8_1_4_3,8,4
        '''CFloat8_1_5_2,8,5
        '''bfloat16-BF16,16,8
        '''NVIDIA-TF32,19,8
        '''Enflame-EF32,20,8
        '''AMD-FP24,24,7
        '''Pixar-PXR24,24,8
        '''KNX_Float16,16,4
        ''' 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property floatpoint() As String
            Get
                Return ResourceManager.GetString("floatpoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似                     GNU GENERAL PUBLIC LICENSE
        '''                       Version 3, 29 June 2007
        '''
        ''' Copyright (C) 2007 Free Software Foundation, Inc. &lt;https://fsf.org/&gt;
        ''' Everyone is permitted to copy and distribute verbatim copies
        ''' of this license document, but changing it is not allowed.
        '''
        '''                            Preamble
        '''
        '''  The GNU General Public License is a free, copyleft license for
        '''software and other kinds of works.
        '''
        '''  The licenses for most software and other practical works are designed
        '''t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property gpl_3_0() As String
            Get
                Return ResourceManager.GetString("gpl_3_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 GNU通用公共许可协议
        '''第三版，2007年6月29日
        '''版权所有 © 2007 自由软件基金会 &lt;http://fsf.org/&gt;
        '''任何人皆可复制和发布本协议的完整副本，但不得修改
        '''
        '''【译者声明】
        '''
        '''　　This is an unofficial translation of the GNU General Public License into Chinese. It was not published by the Free Software Foundation, and does not legally state the distribution terms for software that uses the GNU GPL--only the original English text of the GNU GPL does that. However, we hope that this translation will help Chinese speakers understand the GNU GPL better.
        '''　　这是GNU通用公共许可协议的一份非官方中文翻译，并 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property gpl_3_0_zh_CN() As String
            Get
                Return ResourceManager.GetString("gpl_3_0_zh_CN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property gplv3_or_later() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gplv3_or_later", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property OSF_logo_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OSF_logo_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
